### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Gertkeno/to-the-core#1]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by Gertkeno** [comment]
![image](https://github.com/Gertkeno/to-the-core/assets/15616419/0276beab-24f9-4cdc-81ab-5db40355c647)

**Comment by TechnologyClassroom** [comment]
I am not a bot.

**Comment by Gertkeno** [comment]
01110011011011110010000001111001011011110111010100100000011100110110000101111001

**Comment by TechnologyClassroom** [comment]
You don't have to believe me. Let me know if you needs some licensing help in the future. Have a good one!
